services:
  app:
    build:
      context: .
    ports:
      - "8080:4000"
    volumes:
      - .:/app
    networks:
      - app
    depends_on:
      - postgres
  postgres:
    image: "postgres:15"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  database:
